apiVersion: v1
kind: Service
metadata:
  name: {{ include "neurorecovery-backend-chart.name" . }}-balancer
spec:
  selector:
    app.kubernetes.io/name: {{ include "neurorecovery-backend-chart.name" . }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: LoadBalancer
